# Generated by Django 4.2.7 on 2025-11-05 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_delivery', 'Nouvelle livraison'), ('delivery_accepted', 'Livraison acceptée'), ('delivery_rejected', 'Livraison refusée'), ('delivery_status_change', 'Changement de statut'), ('payment_received', 'Paiement reçu'), ('rating_received', 'Notation reçue'), ('system', 'Notification système'), ('promo', 'Promotion')], db_index=True, help_text='Type de notification', max_length=50)),
                ('title', models.CharField(help_text='Titre de la notification', max_length=255)),
                ('body', models.TextField(help_text='Corps du message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (delivery_id, action, etc.)')),
                ('action', models.CharField(blank=True, help_text='Action à effectuer (open_delivery_details, etc.)', max_length=100)),
                ('action_url', models.CharField(blank=True, help_text='URL de deep linking', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Notification lue ou non')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date de lecture', null=True)),
                ('sent_via_fcm', models.BooleanField(default=True, help_text='Envoyée via FCM ou notification in-app uniquement')),
                ('fcm_message_id', models.CharField(blank=True, help_text='ID du message FCM (pour tracking)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Notification',
                'verbose_name_plural': 'Historique Notifications',
                'db_table': 'notification_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_38d9df_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_a5434b_idx'), models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_137c51_idx')],
            },
        ),
    ]
