# Generated by Django 4.2.7 on 2025-10-30 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonePricingMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_weight_included', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_matrix', to='pricing.pricingzone')),
                ('origin_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_matrix', to='pricing.pricingzone')),
            ],
            options={
                'verbose_name': 'Matrice de Tarification de Zone',
                'verbose_name_plural': 'Matrices de Tarification de Zones',
                'db_table': 'zone_pricing_matrix',
                'unique_together': {('origin_zone', 'destination_zone', 'effective_from')},
            },
        ),
    ]
