# Generated by Django 4.2.7 on 2025-10-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingzone',
            options={'verbose_name': 'Zone Tarifaire', 'verbose_name_plural': 'Zones Tarifaires'},
        ),
        migrations.AlterModelOptions(
            name='zonepricingmatrix',
            options={'verbose_name': 'Tarification Zone', 'verbose_name_plural': 'Tarifications Zones'},
        ),
        migrations.AlterUniqueTogether(
            name='zonepricingmatrix',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='pricingzone',
            table='pricing_zones',
        ),
    ]
