# Generated by Django 4.2.7 on 2025-10-30 16:37

import apps.deliveries.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default=apps.deliveries.models.generate_tracking_number, max_length=50, unique=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_commune', models.CharField(max_length=100)),
                ('delivery_quartier', models.CharField(blank=True, max_length=100)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('package_description', models.TextField(blank=True)),
                ('package_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('package_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('package_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('package_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_alternative_phone', models.CharField(blank=True, max_length=20)),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_method', models.CharField(choices=[('prepaid', 'Prépayé'), ('cod', 'Paiement à la livraison')], max_length=20)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending_assignment', "En attente d'assignation"), ('assigned', 'Assigné'), ('pickup_in_progress', 'Enlèvement en cours'), ('picked_up', 'Colis récupéré'), ('in_transit', 'En livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending_assignment', max_length=50)),
                ('scheduling_type', models.CharField(choices=[('immediate', 'Immédiat'), ('scheduled', 'Planifié')], default='immediate', max_length=20)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('signature_url', models.CharField(blank=True, max_length=500)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('delivery_notes', models.TextField(blank=True)),
                ('delivery_confirmation_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='drivers.driver')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='merchants.merchant')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.merchantaddress')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
