# Generated by Django 4.2.7 on 2025-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pickup_commune',
            field=models.CharField(blank=True, help_text='Commune de départ (ex: Cocody)', max_length=100),
        ),
    ]
