# Generated by Django 4.2.7 on 2025-11-05 22:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_add_vehicle_plate_validator'),
        ('merchants', '0002_merchant_documents_url_merchant_id_document_and_more'),
        ('deliveries', '0002_delivery_pickup_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Note de 1 à 5', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0, message='La note minimum est 1'), django.core.validators.MaxValueValidator(5.0, message='La note maximum est 5')])),
                ('comment', models.TextField(blank=True, help_text='Commentaire optionnel du marchand')),
                ('punctuality_rating', models.IntegerField(blank=True, help_text='Ponctualité (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(blank=True, help_text='Professionnalisme (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('care_rating', models.IntegerField(blank=True, help_text='Soin du colis (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(help_text='Livraison évaluée', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='deliveries.delivery')),
                ('driver', models.ForeignKey(help_text='Livreur évalué', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='drivers.driver')),
                ('merchant', models.ForeignKey(help_text='Marchand qui donne la note', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Évaluation Livraison',
                'verbose_name_plural': 'Évaluations Livraisons',
                'db_table': 'delivery_ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'rating'], name='delivery_ra_driver__cc213e_idx'), models.Index(fields=['merchant', 'created_at'], name='delivery_ra_merchan_fa2188_idx')],
            },
        ),
    ]
