# Generated by Django 4.2.7 on 2025-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_add_delivery_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='required_vehicle_type',
            field=models.CharField(blank=True, choices=[('', 'Indifférent'), ('moto', 'Moto'), ('voiture', 'Voiture'), ('tricycle', 'Tricycle'), ('camionnette', 'Camionnette')], help_text='Type de véhicule requis (moto, voiture, tricycle, camionnette)', max_length=50),
        ),
    ]
