# Generated by Django 4.2.7 on 2025-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delivery_required_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pickup_address_details',
            field=models.CharField(blank=True, help_text='Adresse complète si différente des adresses sauvegardées', max_length=255),
        ),
    ]
