# Generated by Django 4.2.7 on 2025-12-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_documents_url_merchant_id_document_and_more'),
        ('deliveries', '0005_delivery_pickup_address_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='merchants.merchant'),
        ),
    ]
