# Generated by Django 4.2.7 on 2025-12-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0006_alter_delivery_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
