# Generated by Django 4.2.7 on 2025-12-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_add_created_by_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=50),
        ),
    ]
