# Generated by Django 4.2.7 on 2025-12-06 23:44

from django.db import migrations


def convert_statuses(apps, schema_editor):
    """Convertit les anciens statuts aux nouveaux"""
    Delivery = apps.get_model('deliveries', 'Delivery')
    
    # Tous les statuts "en attente" deviennent 'pending'
    Delivery.objects.filter(status__in=['pending_assignment', 'assigned']).update(status='pending')
    
    # Tous les statuts "en cours" deviennent 'in_progress'
    Delivery.objects.filter(status__in=['pickup_in_progress', 'picked_up', 'in_transit']).update(status='in_progress')
    
    # 'delivered' reste 'delivered'
    # 'cancelled' reste 'cancelled'


def reverse_convert(apps, schema_editor):
    """Impossible d'inverser, on revient à 'pending' par défaut"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_delivery_status'),
    ]

    operations = [
        migrations.RunPython(convert_statuses, reverse_convert),
    ]
