# Generated by Django 4.2.7 on 2025-12-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_convert_delivery_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Adresse complète (optionnel - la commune et quartier suffisent)', max_length=255),
        ),
    ]
