# Generated by Django 4.2.7 on 2025-12-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_make_delivery_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pickup_quartier',
            field=models.CharField(blank=True, help_text='Quartier de départ pour plus de précision', max_length=100),
        ),
    ]
