# Generated by Django 4.2.7 on 2025-12-07 01:11

from django.db import migrations


def normalize_communes(apps, schema_editor):
    """Normaliser les noms de communes pour correspondre aux zones"""
    Delivery = apps.get_model('deliveries', 'Delivery')
    
    mapping = {
        'COCODY': 'Cocody',
        'PORT-BOUET': 'Port-Bouët',
        'SONGON': 'Songon',
        'TREICHVILLE': 'Treichville',
    }
    
    for old_name, new_name in mapping.items():
        count = Delivery.objects.filter(delivery_commune__iexact=old_name).update(
            delivery_commune=new_name
        )
        if count > 0:
            print(f"  ✓ Normalisé {count} livraisons: {old_name} -> {new_name}")


def reverse_normalize(apps, schema_editor):
    """Reverse: retourner au format MAJUSCULES"""
    Delivery = apps.get_model('deliveries', 'Delivery')
    
    mapping = {
        'Cocody': 'COCODY',
        'Port-Bouët': 'PORT-BOUET',
        'Songon': 'SONGON',
        'Treichville': 'TREICHVILLE',
    }
    
    for old_name, new_name in mapping.items():
        Delivery.objects.filter(delivery_commune=old_name).update(
            delivery_commune=new_name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_add_pickup_quartier'),
    ]

    operations = [
        migrations.RunPython(normalize_communes, reverse_normalize),
    ]
