# Generated by hand
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_normalize_delivery_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_source',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
