# Generated by Django 4.2.7 on 2025-12-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_normalize_delivery_communes'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE deliveries "
                "ADD COLUMN IF NOT EXISTS distance_source varchar(50) NULL;"
            ),
            reverse_sql=(
                "ALTER TABLE deliveries DROP COLUMN IF EXISTS distance_source;"
            ),
        ),
    ]
