# Generated by Django 4.2.7 on 2025-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_normalize_delivery_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
