# Generated by Django 4.2.7 on 2025-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_delivery_distance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pickup_photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_signature_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
