# Generated by Django 4.2.7 on 2025-12-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_delivery_pickup_photo_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'created_at'], name='delivery_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'status'], name='delivery_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['merchant', 'status'], name='delivery_merchant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pickup_commune'], name='delivery_pickup_commune_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_commune'], name='delivery_delivery_commune_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['created_by', 'status'], name='delivery_createdby_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tracking_number'], name='delivery_tracking_idx'),
        ),
    ]
