# Generated by Django 4.2.7 on 2025-12-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_allow_null_merchant_in_rating'),
        ('deliveries', '0015_add_delivery_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrating',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Marchand qui donne la note (null si particulier)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='merchants.merchant'),
        ),
    ]
