# Generated by Django 4.2.7 on 2025-12-12 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0016_allow_null_merchant_in_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrating',
            name='rated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a donné la note (merchant ou particulier)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire optionnel'),
        ),
    ]
