# Generated by Django 4.2.7 on 2025-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0017_add_rated_by_to_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant que le driver va gagner (75% par défaut)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de la commission LeBeni's en CFA", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text="Pourcentage de commission LeBeni's (défaut: 25%)", max_digits=5),
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight_confirmed',
            field=models.BooleanField(default=False, help_text="True si le poids a été explicitement confirmé par l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix total payé par le client', max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='package_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, help_text='Poids en kg. Défaut: 5kg. Obligatoire si > 10kg', max_digits=5, null=True),
        ),
    ]
