// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyyieEU8GtMPyJMXyytrFV6jRPi2wBdfs',
    appId: '1:949402679677:web:b07fb0ae6b9b8f196af414',
    messagingSenderId: '949402679677',
    projectId: 'lebenis-project',
    authDomain: 'lebenis-project.firebaseapp.com',
    storageBucket: 'lebenis-project.firebasestorage.app',
    measurementId: 'G-5S27M8TX6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDYurI5ka8cPM-HWTzV2wfUgRGOQVo6I',
    appId: '1:949402679677:android:2fa9f26f76d00a6b6af414',
    messagingSenderId: '949402679677',
    projectId: 'lebenis-project',
    storageBucket: 'lebenis-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Ig-PUj7y2s1_lzyQalSmrT9sxA9Xos',
    appId: '1:949402679677:ios:d6b306c470325e556af414',
    messagingSenderId: '949402679677',
    projectId: 'lebenis-project',
    storageBucket: 'lebenis-project.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Ig-PUj7y2s1_lzyQalSmrT9sxA9Xos',
    appId: '1:949402679677:ios:d6b306c470325e556af414',
    messagingSenderId: '949402679677',
    projectId: 'lebenis-project',
    storageBucket: 'lebenis-project.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyyieEU8GtMPyJMXyytrFV6jRPi2wBdfs',
    appId: '1:949402679677:web:b00b38fcd0dc429f6af414',
    messagingSenderId: '949402679677',
    projectId: 'lebenis-project',
    authDomain: 'lebenis-project.firebaseapp.com',
    storageBucket: 'lebenis-project.firebasestorage.app',
    measurementId: 'G-KXMTPKVYWG',
  );
}
