# Generated by Django 4.2.7 on 2025-11-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
