# Generated by Django 4.2.7 on 2025-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['email', 'created_at'], name='password_re_email_cdad28_idx'),
        ),
    ]
