# Generated by Django 4.2.7 on 2025-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_ip_address_to_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('merchant', 'Commerçant'), ('driver', 'Livreur'), ('individual', 'Particulier'), ('admin', 'Administrateur')], max_length=20),
        ),
    ]
