# Generated by Django 4.2.7 on 2025-10-30 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_license', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('tricycle', 'Tricycle')], max_length=50)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('vehicle_capacity_kg', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Zone Livreur',
                'verbose_name_plural': 'Zones Livreurs',
                'db_table': 'driver_zones',
                'unique_together': {('driver', 'commune')},
            },
        ),
    ]
