# Generated by Django 4.2.7 on 2025-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('offline', 'Hors ligne')], default='offline', help_text='Statut de disponibilité: available, busy, offline', max_length=20),
        ),
    ]
