# Generated by Django 4.2.7 on 2025-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='identity_card_back',
            field=models.URLField(blank=True, help_text='Photo verso CNI', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='identity_card_front',
            field=models.URLField(blank=True, help_text='Photo recto CNI', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='identity_card_number',
            field=models.CharField(blank=True, help_text='Numéro CNI/Passeport', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text='Liste des langues parlées'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('orange', 'Orange Money'), ('mtn', 'MTN Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='previous_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_gray_card',
            field=models.URLField(blank=True, help_text='Carte grise', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_inspection_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_insurance',
            field=models.URLField(blank=True, help_text='Document assurance', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_technical_inspection',
            field=models.URLField(blank=True, help_text='Visite technique', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text="Années d'expérience en livraison"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('tricycle', 'Tricycle'), ('camionnette', 'Camionnette')], max_length=50),
        ),
    ]
