# Generated by Django 4.2.7 on 2025-11-05 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_add_driver_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_registration',
            field=models.CharField(blank=True, help_text="Plaque d'immatriculation (ex: AB 1234 CD)", max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_plate', message="Format invalide. Formats acceptés: CEDEAO (AB 1234 CD), Sénégal (DK 1234 A), Côte d'Ivoire (12 AB 3456)", regex='^([A-Z]{2}\\s\\d{4}\\s[A-Z]{2}|[A-Z]{2}\\s\\d{4}\\s[A-Z]|\\d{2}\\s[A-Z]{2}\\s\\d{4})$')]),
        ),
    ]
