# Generated by Django 4.2.7 on 2025-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_add_vehicle_plate_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='break_started_at',
            field=models.DateTimeField(blank=True, help_text='Heure de début de la pause', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_on_break',
            field=models.BooleanField(default=False, help_text='Indique si le livreur est en pause'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_break_reset',
            field=models.DateField(blank=True, help_text='Dernière réinitialisation du compteur de pauses', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_break_duration_today',
            field=models.DurationField(blank=True, help_text="Durée totale des pauses aujourd'hui", null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('on_break', 'En pause'), ('offline', 'Hors ligne')], default='offline', help_text='Statut de disponibilité: available, busy, offline', max_length=20),
        ),
    ]
