# Generated by Django 4.2.7 on 2025-11-06 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_add_break_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude GPS', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude GPS', max_digits=11)),
                ('accuracy', models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Vitesse en m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction en degrés (0-360)', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude en mètres', null=True)),
                ('driver_status', models.CharField(help_text='Statut du chauffeur au moment de la mise à jour', max_length=20)),
                ('is_moving', models.BooleanField(default=False, help_text='Indique si le chauffeur est en mouvement')),
                ('battery_level', models.IntegerField(blank=True, help_text='Niveau de batterie (0-100)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Horodatage de la mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Location Update',
                'verbose_name_plural': 'Location Updates',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='drivers_loc_driver__2dbd59_idx'), models.Index(fields=['driver', 'driver_status'], name='drivers_loc_driver__c57f02_idx'), models.Index(fields=['-timestamp'], name='drivers_loc_timesta_99b3c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationTrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_updates', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(blank=True, null=True)),
                ('total_distance_km', models.FloatField(default=0.0, help_text='Distance totale parcourue pendant la session')),
                ('initial_battery_level', models.IntegerField(blank=True, null=True)),
                ('final_battery_level', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Tracking Session',
                'verbose_name_plural': 'Tracking Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['driver', '-started_at'], name='drivers_loc_driver__1f8403_idx')],
            },
        ),
    ]
