# Generated by Django 4.2.7 on 2025-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_add_location_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_vignette',
            field=models.URLField(blank=True, help_text='Document vignette', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_vignette_expiry',
            field=models.DateField(blank=True, help_text="Date d'expiration de la vignette", null=True),
        ),
    ]
