# Generated by Django 4.2.7 on 2025-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driver_vehicle_vignette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
