# Generated by Django 4.2.7 on 2025-11-06 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0003_add_delivery_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('delivery', 'Livraison (Driver-Client)'), ('support', 'Support (Driver-Admin)')], db_index=True, default='delivery', max_length=20)),
                ('firebase_path', models.CharField(db_index=True, help_text='Chemin dans Firebase: /chats/{uuid}', max_length=255, unique=True)),
                ('last_message_text', models.TextField(blank=True, help_text='Dernier message')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_sender_id', models.UUIDField(blank=True, null=True)),
                ('driver_unread_count', models.IntegerField(default=0)),
                ('other_user_unread_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, help_text='Livraison concernée (si room_type=delivery)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='deliveries.delivery')),
                ('driver', models.ForeignKey(help_text='Livreur participant', on_delete=django.db.models.deletion.CASCADE, related_name='driver_chats', to=settings.AUTH_USER_MODEL)),
                ('other_user', models.ForeignKey(help_text='Client ou Admin', on_delete=django.db.models.deletion.CASCADE, related_name='other_user_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('location', 'Position GPS'), ('system', 'Message système')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, help_text='Contenu du message')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced_to_firebase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['driver', 'is_active'], name='chat_rooms_driver__1e89c5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['other_user', 'is_active'], name='chat_rooms_other_u_1cc509_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['delivery'], name='chat_rooms_deliver_30227d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-last_message_at'], name='chat_rooms_last_me_e2b45f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('driver', 'other_user', 'delivery')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='chat_messag_chat_ro_b6bf60_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__7a605a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_6e9c3b_idx'),
        ),
    ]
