"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
from urllib.parse import urlparse, parse_qsl
import os
from dotenv import load_dotenv

load_dotenv()

# Sentry initialization (development + production)
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,  # 10% des transactions trackées
            send_default_pii=False,   # Ne pas envoyer d'infos personnelles
            environment=config('ENVIRONMENT', default='development'),
        )
    except ImportError:
        # Sentry SDK non installé - ignorer
        pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

   # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',  # Pour l'authentification JWT
    'rest_framework_simplejwt.token_blacklist',  # AJOUTÉ : Pour gérer la blacklist des tokens (logout)
    'corsheaders',  # Pour gérer les requêtes cross-origin (depuis Flutter)
    'cloudinary_storage',  # Cloudinary pour stockage images (DOIT être AVANT django.contrib.staticfiles)
    'cloudinary',  # Cloudinary SDK
    'fcm_django',   # Pour les notifications push
    'drf_yasg',     # Pour la documentation Swagger
    'django_celery_beat',  # Pour les tâches planifiées (cron jobs)
    'django_celery_results',  # Pour stocker les résultats des tâches
    
    # Local apps
    'apps.authentication',
    'apps.merchants',
    'apps.drivers',
    'apps.individuals',  # Particuliers
    'apps.deliveries',
    'apps.pricing',
    'apps.notifications',
    'apps.payments',
    'apps.chat',  # Phase 3 - Chat temps réel
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware en haut
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise pour static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'apps.core.middleware.DebugAuthMiddleware',  # ⚠️ DÉSACTIVÉ en production (à réactiver uniquement en dev)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Replace the DATABASES section of your settings.py with this
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Custom user model
AUTH_USER_MODEL = 'authentication.User'

#Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    # Handler d'exceptions personnalisé pour des messages clairs en français
    'EXCEPTION_HANDLER': 'apps.core.exception_handler.custom_exception_handler',
}   


# JWT Settings avancés
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# CORS Settings - Updated 2025-11-04
#CORS_ALLOWED_ORIGINS = [
#    "http://localhost:3000",
#    "http://127.0.0.1:3000",
#    "http://localhost:8000",
#    "http://127.0.0.1:8000",
#    "http://127.0.0.1:8080",
#    "http://localhost:8080",
#]
CORS_ALLOW_CREDENTIALS = True

# ⚠️ CORS_ALLOW_ALL_ORIGINS désactivé pour la sécurité en production
# Utiliser CORS_ALLOWED_ORIGINS dans production.py à la place
CORS_ALLOW_ALL_ORIGINS = False


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'HEAD',
]
#fin test

# Firebase Cloud Messaging
FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": config('FCM_SERVER_KEY', default=''),
}

# Firebase Admin SDK V1 (Recommandé)
FIREBASE_CREDENTIALS_PATH = config('FIREBASE_CREDENTIALS_PATH', default='config/firebase/service-account.json')

# Firebase Realtime Database (Phase 3 - Chat)
FIREBASE_DATABASE_URL = config('FIREBASE_DATABASE_URL', default='')

# Google Maps
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')

# Sentry (monitoring erreurs)
SENTRY_DSN = config('SENTRY_DSN', default='')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Basic logging configuration with optional JSON formatter (python-json-logger)
try:
    # Prefer structured JSON formatter when available
    from pythonjsonlogger.jsonlogger import JsonFormatter  # type: ignore
    _HAS_JSON_LOGGER = True
except Exception:
    _HAS_JSON_LOGGER = False

if _HAS_JSON_LOGGER:
    _json_formatter = {'()': 'pythonjsonlogger.jsonlogger.JsonFormatter', 'fmt': '%(levelname)s %(asctime)s %(name)s %(message)s'}
else:
    _json_formatter = {'format': '{levelname} {asctime} {module} {message}', 'style': '{'}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'json': _json_formatter,
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'console_json': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# CLOUDINARY CONFIGURATION (Image Storage)
# ============================================================================
# Configuration sécurisée via variables d'environnement
# Créer compte gratuit: https://cloudinary.com/users/register/free
# Limites gratuites: 25 crédits/mois, 25GB stockage, 25GB bande passante

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
    'SECURE': True,  # Toujours utiliser HTTPS
}

# Validation des uploads
CLOUDINARY_UPLOAD_OPTIONS = {
    'folder': 'lebenis',  # Dossier dans Cloudinary
    'resource_type': 'image',  # Type de ressource
    'allowed_formats': ['jpg', 'jpeg', 'png', 'webp'],  # Formats autorisés
    'transformation': [
        {'width': 1024, 'height': 1024, 'crop': 'limit'},  # Max dimensions
        {'quality': 'auto:good'},  # Compression automatique
        {'fetch_format': 'auto'},  # Format optimal (WebP si supporté)
    ],
}

# Configuration pour les différents types d'images
CLOUDINARY_PROFILE_PHOTO_OPTIONS = {
    'folder': 'lebenis/profiles',
    'resource_type': 'image',
    'allowed_formats': ['jpg', 'jpeg', 'png', 'webp'],
    'transformation': [
        {'width': 512, 'height': 512, 'crop': 'fill', 'gravity': 'face'},  # Avatar carré centré sur visage
        {'quality': 'auto:good'},
        {'fetch_format': 'auto'},
    ],
}

CLOUDINARY_DOCUMENT_OPTIONS = {
    'folder': 'lebenis/documents',
    'resource_type': 'image',
    'allowed_formats': ['jpg', 'jpeg', 'png', 'pdf'],
    'transformation': [
        {'width': 2048, 'height': 2048, 'crop': 'limit'},
        {'quality': 'auto:best'},  # Meilleure qualité pour documents
    ],
}

# Swagger Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,  # ✅ Désactive l'auth de session dans Swagger
}


# Email Configuration (pour production)
# Render Free Tier bloque SMTP, utiliser l'API SendGrid via HTTP
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')

if SENDGRID_API_KEY:
    # Utiliser l'API SendGrid (HTTP - non bloquée par Render)
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    SENDGRID_SANDBOX_MODE_IN_DEBUG = DEBUG
else:
    # Fallback SMTP (pour développement local ou plans payants Render)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.sendgrid.net')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))  # Port TLS
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'apikey')
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY

# Configuration commune
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'yah.kouakou24@inphb.ci')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'yah.kouakou24@inphb.ci')

# En développement sans clé API, utiliser console
if not SENDGRID_API_KEY and DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# ==============================================================================
# MOBILE MONEY CONFIGURATION (Phase 2)
# ==============================================================================

# Orange Money API (Côte d'Ivoire)
ORANGE_MONEY_CLIENT_ID = config('ORANGE_MONEY_CLIENT_ID', default='')
ORANGE_MONEY_CLIENT_SECRET = config('ORANGE_MONEY_CLIENT_SECRET', default='')
ORANGE_MONEY_MERCHANT_CODE = config('ORANGE_MONEY_MERCHANT_CODE', default='')
ORANGE_MONEY_ENVIRONMENT = config('ORANGE_MONEY_ENVIRONMENT', default='sandbox')

# MTN Mobile Money API (Côte d'Ivoire)
MTN_MOMO_API_USER = config('MTN_MOMO_API_USER', default='')
MTN_MOMO_API_KEY = config('MTN_MOMO_API_KEY', default='')
MTN_MOMO_SUBSCRIPTION_KEY = config('MTN_MOMO_SUBSCRIPTION_KEY', default='')
MTN_MOMO_ENVIRONMENT = config('MTN_MOMO_ENVIRONMENT', default='sandbox')


# ==============================================================================
# CELERY CONFIGURATION (Phase 2 - Automated Daily Payouts)
# ==============================================================================

# Celery Broker (Redis)
from urllib.parse import urlparse
import os

# Read raw redis url (used by other services too)
RAW_REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# Normalize: if broker/result-specific env vars are set, prefer them
_env_broker = os.environ.get('CELERY_BROKER_URL') or os.environ.get('BROKER_URL')
_env_result = os.environ.get('CELERY_RESULT_BACKEND')

# If explicit CELERY_* env vars present use them, else fall back to RAW_REDIS_URL
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=_env_broker or RAW_REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=_env_result or RAW_REDIS_URL)

# If RAW_REDIS_URL uses redis:// but contains SSL query params or an env toggle,
# promote it to rediss:// to satisfy Redis client expectations.
require_redis_ssl = os.getenv('REQUIRE_REDIS_SSL', '').lower() in ('1', 'true', 'yes')
parsed = urlparse(RAW_REDIS_URL)
if parsed.scheme == 'redis' and (require_redis_ssl or 'ssl' in parsed.query or 'ssl_cert_reqs' in parsed.query):
    # Promote the scheme for both broker/result when they match the raw url
    if CELERY_BROKER_URL == RAW_REDIS_URL:
        CELERY_BROKER_URL = RAW_REDIS_URL.replace('redis://', 'rediss://', 1)
    if CELERY_RESULT_BACKEND == RAW_REDIS_URL:
        CELERY_RESULT_BACKEND = RAW_REDIS_URL.replace('redis://', 'rediss://', 1)

# Configure SSL options only when using rediss:// (TLS)
import ssl
if urlparse(CELERY_BROKER_URL).scheme.startswith('rediss'):
    CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
else:
    CELERY_BROKER_USE_SSL = None

if urlparse(CELERY_RESULT_BACKEND).scheme.startswith('rediss'):
    CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
else:
    CELERY_REDIS_BACKEND_USE_SSL = None

# Celery Settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Abidjan'  # UTC+0 (Côte d'Ivoire)
CELERY_ENABLE_UTC = False

# Task Configuration
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max par tâche
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Warning à 25 minutes

# Celery Beat Schedule (Tâches planifiées)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Paiements quotidiens des drivers à 23h59
    'daily-driver-payouts': {
        'task': 'apps.payments.tasks.process_daily_payouts',
        'schedule': crontab(hour=23, minute=59),  # Chaque jour à 23h59
        'options': {
            'expires': 60 * 60,  # Expire après 1h si non exécutée
        }
    },
    
    # Vérification des payouts en attente toutes les heures
    'check-pending-payouts': {
        'task': 'apps.payments.tasks.check_pending_payouts',
        'schedule': crontab(minute=0),  # Toutes les heures à :00
        'options': {
            'expires': 50 * 60,  # Expire après 50 min
        }
    },
    
    # Reset des durées de pause à minuit
    'reset-daily-break-durations': {
        'task': 'apps.payments.tasks.reset_daily_break_durations',
        'schedule': crontab(hour=0, minute=0),  # Chaque jour à 00h00
        'options': {
            'expires': 30 * 60,  # Expire après 30 min
        }
    },
}

# Logging Celery
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# --- Diagnostic helper: log resolved broker/backend (sanitized) at startup ---
import logging
_logger = logging.getLogger(__name__)

def _mask_redis_url(url: str) -> str:
    """Return a sanitized version of a redis/rediss URL for logs (hide credentials)."""
    try:
        p = urlparse(url)
        if p.username or p.password:
            # hide userinfo
            netloc = '***:***@' + (p.hostname or '')
            if p.port:
                netloc += f':{p.port}'
        else:
            netloc = f"{p.hostname or ''}{(':'+str(p.port)) if p.port else ''}"
        return f"{p.scheme}://{netloc}{p.path or ''}"
    except Exception:
        return url

# Log the resolved values once (info-level). In production logs this helps
# confirm which broker the Django/Celery process will attempt to use.
try:
    _logger.info("Resolved Celery broker: %s", _mask_redis_url(CELERY_BROKER_URL))
    _logger.info("Resolved Celery result backend: %s", _mask_redis_url(CELERY_RESULT_BACKEND))
except Exception:
    _logger.debug("Could not log Celery broker/result backend (masking failed)")
