# Generated by Django 4.2.7 on 2025-11-01 20:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_merchant_documents_url_merchant_id_document_and_more'),
        ('deliveries', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('card', 'Carte bancaire')], max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='deliveries.delivery')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de factures',
                'db_table': 'invoice_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces')], max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Paiement Livreur',
                'verbose_name_plural': 'Paiements Livreurs',
                'db_table': 'driver_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_earning', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('distance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('time_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('quality_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('penalty_reason', models.TextField(blank=True)),
                ('total_earning', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('paid', 'Payé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_earning', to='deliveries.delivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Revenu Livreur',
                'verbose_name_plural': 'Revenus Livreurs',
                'db_table': 'driver_earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['merchant', 'status'], name='invoices_merchan_23814f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period_start', 'period_end'], name='invoices_period__f31005_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpayment',
            index=models.Index(fields=['driver', 'status'], name='driver_paym_driver__13a853_idx'),
        ),
        migrations.AddIndex(
            model_name='driverearning',
            index=models.Index(fields=['driver', 'status'], name='driver_earn_driver__ff51e4_idx'),
        ),
    ]
