# Generated by Django 4.2.7 on 2025-11-05 22:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_add_vehicle_plate_validator'),
        ('deliveries', '0003_add_delivery_rating'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant total de la livraison (FCFA)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Commission LeBeni's (10%)", max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de transaction Mobile Money', max_digits=10)),
                ('driver_amount', models.DecimalField(decimal_places=2, help_text='Montant que le livreur recevra (90%)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('cash', 'Cash (COD)')], help_text='Méthode de paiement utilisée', max_length=20)),
                ('transaction_type', models.CharField(choices=[('collection', 'Collecte client'), ('disbursement', 'Versement livreur')], default='collection', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='ID de transaction Mobile Money (Orange/MTN)', max_length=255, null=True, unique=True)),
                ('reference', models.CharField(blank=True, help_text="Référence interne LeBeni's", max_length=100)),
                ('external_reference', models.CharField(blank=True, help_text='Référence externe API Mobile Money', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (réponse API, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date de complétion du paiement', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text="Date d'échec du paiement", null=True)),
                ('delivery', models.OneToOneField(help_text='Livraison associée à ce paiement', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_payment', to='deliveries.delivery')),
                ('driver', models.ForeignKey(help_text='Livreur qui recevra le paiement', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_payments', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Paiement Mobile Money',
                'verbose_name_plural': 'Paiements Mobile Money',
                'db_table': 'mobile_money_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_date', models.DateField(db_index=True, help_text='Date du versement (jour des livraisons)')),
                ('total_deliveries', models.IntegerField(default=0, help_text='Nombre de livraisons complétées ce jour')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gains totaux avant déductions', max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Total commission LeBeni's (10%)", max_digits=10)),
                ('transaction_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total frais Mobile Money', max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant net versé au livreur (90%)', max_digits=10)),
                ('payment_method', models.CharField(help_text='Méthode de versement (orange_money, mtn_money, etc.)', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transaction Mobile Money du versement', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('partially_failed', 'Partiellement échoué')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date de traitement du versement', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payouts', to='drivers.driver')),
                ('payments', models.ManyToManyField(help_text='Paiements individuels inclus dans ce versement', related_name='daily_payouts', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Versement Journalier',
                'verbose_name_plural': 'Versements Journaliers',
                'db_table': 'daily_payouts',
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('collection', 'Collecte'), ('disbursement', 'Versement'), ('refund', 'Remboursement'), ('commission', 'Commission'), ('fee', 'Frais')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('external_reference', models.CharField(blank=True, help_text='Référence externe (Orange Money, MTN, etc.)', max_length=255)),
                ('provider', models.CharField(blank=True, help_text='Fournisseur Mobile Money', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro ayant effectué la transaction', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Réponse complète de l'API Mobile Money")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='drivers.driver')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'transaction_type', 'created_at'], name='transaction_driver__ab63d1_idx'), models.Index(fields=['status', 'created_at'], name='transaction_status_e0898f_idx'), models.Index(fields=['provider', 'status'], name='transaction_provide_335edd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['driver', 'status'], name='mobile_mone_driver__250113_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'status'], name='mobile_mone_created_d443fc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='mobile_mone_payment_d5b499_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypayout',
            index=models.Index(fields=['driver', 'payout_date'], name='daily_payou_driver__bded47_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypayout',
            index=models.Index(fields=['status', 'payout_date'], name='daily_payou_status_2f9096_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypayout',
            unique_together={('driver', 'payout_date')},
        ),
    ]
