# Generated by Django 4.2.7 on 2025-11-10 16:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_mobile_money_payment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayout',
            name='net_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant net versé au livreur (80%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypayout',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Total commission LeBeni's (20%)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='driver_amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant que le livreur recevra (80%)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Commission LeBeni's (20%)", max_digits=10),
        ),
    ]
