# Generated by Django 4.2.7 on 2025-10-30 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commerçant',
                'verbose_name_plural': 'Commerçants',
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='MerchantAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_name', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='Abidjan', max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Adresse Commerçant',
                'verbose_name_plural': 'Adresses Commerçants',
                'db_table': 'merchant_addresses',
            },
        ),
    ]
