# Generated by Django 4.2.7 on 2025-11-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='documents_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL des documents'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_document',
            field=models.CharField(blank=True, max_length=500, verbose_name="Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rccm_document',
            field=models.CharField(blank=True, max_length=500, verbose_name='Document RCCM'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du rejet'),
        ),
    ]
