# Generated by Django 4.2.7 on 2025-12-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_documents_url_merchant_id_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commerçant', 'verbose_name_plural': 'Commerçants'},
        ),
    ]
